apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backster
  description: a simple Backstage managed service in golang
  annotations:
    backstage.io/techdocs-ref: dir:.
    jfrog.io/pipeline-name: intro_hello_world
    argocd/app-name: test
  labels:
    version: 2.3.4
  tags:
    - golang
spec:
  type: service
  lifecycle: production
  owner: stagecentral
  system: backstage-workshop
